version: "3.8"
services:
 
    quotemng:
        hostname: quotemng
        build: .
        image: quotemanager
        container_name: quotemng
        environment:
            - stockManagerUrl=stockmng
            - quoteManagerUrl=quotemng
            - databaseUrl=mysql
            - SPRING_PROFILES_ACTIVE=prod
        ports:
            - "8081:8081"
        networks:
            - connection1
        depends_on:
            - stockmng
            - mysql
    
    mysql:
        hostname: mysql
        image: mysql:8
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=bootdb
            - MYSQL_PASSWORD=root
        ports:
            - "3306:3306"
            - "33060:33060"
        networks:
            - connection1
    
    stockmng:
        hostname: stockmng
        image: lucasvilela/stock-manager
        container_name: stockmng
        ports:
            - "8080:8080"
        networks:
            - connection1
    

networks:
    connection1:
        driver: bridge